#!/bin/bash
#Le fichier, Répertoire à supprimer est à indiquer (absolu ou relatif) en paramètre de la commande.
#Par défaut, la valeur de answer est vide afin de prompter la confirmation de suppression une première fois.
answer=""

if [ -z $1 ]
then
	echo "Merci d'indiquer le nom ou chemin du fichier à supprimer en entrant la commande."
	exit
fi

while [ "$answer" != "o" ] && [ "$answer" != "n" ]
do
	echo "Êtes - vous certain de vouloir supprimer $1 ? (o/n)"
	read answer
done

if [ $answer = "o" ]
then
	rm -rfv $1
	echo "L'opération de suppression de \"$1\" s'est terminée sans erreur."
elif [ $answer = "n" ]
then
	echo "Suppression de \"$1\" annulée."
fi
